Rtdbin update
readthedocs-fr/code-of-conduct pull request #1
Opened 2021-01-30 17:45 UTC by EnderDragonneau

2021-01-30 17:49 UTC, Aakodal approved these changes

2021-01-30 17:54 UTC, AntoineJT commented on README.md
> +Cela a pour but d'éviter les messages trop longs dans les salons de langage (le bot n'est actif que dans les catégories Développement et Technique).
Les 2 espaces à la fin des phrases et le fait de les remettre à la ligne permettent de l'afficher correctement sur GitHub.
De plus, je préfère l'utilisation d'original ici plutôt que d'originel.
```suggestion
Comme indiqué plus haut, nous réalisons des programmes informatiques avec la communauté. Nous avons notamment réalisé notre propre service de bin.  
Un bot Discord a également été fait pour permettre d'upload automatiquement sur le bin tout snippet de code trop long (à savoir 20 lignes ou plus) ou fichier joint directement sur Discord tout en supprimant le message original.  
En effet, au bout d'un certain nombre de lignes, il est plus facile de lire le code sur un service de bin plutôt que directement dans un salon Discord.  
Cela a pour but d'éviter les messages trop longs dans les salons de langage (le bot n'est actif que dans les catégories Développement et Technique).
```

2021-01-30 17:56 UTC, Mesteery commented on README.md
> +Un bot Discord a également été fait pour permettre d'upload automatiquement sur le bin tout snippet de code trop long (à savoir 20 lignes ou plus) ou fichier joint directement sur Discord tout en sup
```suggestion
Un bot Discord a également été fait pour créer automatiquement un bin à partir de tout snippet de code trop long (à savoir 20 lignes ou plus) ou fichier joint sur Discord tout en supprimant le message originel. En effet, au bout d'un certain nombre de lignes, il est plus facile de lire le code sur un service de bin plutôt que directement dans un salon Discord.  
```

2021-01-30 17:57 UTC, Mesteery commented on README.md
> +Cela a pour but d'éviter les messages trop longs dans les salons de langage (le bot n'est actif que dans les catégories Développement et Technique).
Même si je suis d'accord sur le `original`, j'ai regarder un peu plus profondément sur la différence entre les 2, et `originel` semble plus adapté.

2021-01-30 17:58 UTC, Aakodal commented on README.md
> +Cela a pour but d'éviter les messages trop longs dans les salons de langage (le bot n'est actif que dans les catégories Développement et Technique).
Le CNRTL admet en définition première littéralement une définition identique pour original ou originel.

TL;DR osef, les deux sont valides

2021-01-30 17:59 UTC, EnderDragonneau commented on README.md
> +Cela a pour but d'éviter les messages trop longs dans les salons de langage (le bot n'est actif que dans les catégories Développement et Technique).
Originel est plus beau et me semble aussi plus approprié

2021-01-30 18:02 UTC, Mesteery commented on README.md
> +Cela a pour but d'éviter les messages trop longs dans les salons de langage (le bot n'est actif que dans les catégories Développement et Technique).
Je suis désolé, mais `origina` est beaucoup plus beau.

2021-01-31 10:32 UTC, Aakodal requested changes
Je tiens à ce qu'on rajoute 2-3 trucs :


- les fichiers joints détectés ne sont uploadés que s'ils sont "textuels"

- le bot essaiera de renvoyer toutes les pièces jointes qu'il a pu obtenir dans la limite totale de Discord de 8Mo

- il faut préciser qu'il n'y a aucune garantie quant aux bins générés à partir de blocs de code foireux, avec des échappements de backticks complètement random. Le bot est censé gérer les mêmes cas que Discord, mais il n'y a aucune garantie dessus ; s'ils veulent un bin correct, ils utilisent du markdown correct

- si les membres tiennent vraiment à outre passer le bot, ils peuvent envoyer un premier message puis l'éditer avec leur bloc. Il faut cependant noter qu'en faisant ça, on peut leur reprocher un flood volontaire (puisqu'ils le font en connaissance de cause) et que la modération pourrait les sanctionner pour cela

2021-01-31 11:15 UTC, AntoineJT requested changes
Les 2 espaces à la fin des phrases sont un équivalent à `\` en markdown : ils servent à insérer un retour ligne à la fin de la phrase.
Je ne suis toujours pas d'accord avec originel, enfin, du moins j'aimerai l'avis de plus de monde (moment de ressusciter le module de sondages et le salon éponyme ?).
Je n'étais d'abord pas d'accord avec le fait d'intervertir les deux dernières lignes, mais après relecture et reformulation, je pense qu'il est en effet mieux de les inverser.

2021-01-31 11:15 UTC, AntoineJT commented on README.md
> +Un bot Discord a également été fait pour créer automatiquement un bin à partir de tout snippet de code trop long (à savoir 20 lignes ou plus) ou fichier joint directement sur Discord tout en supprima
```suggestion
Un bot Discord a également été fait pour créer automatiquement un bin à partir de tout snippet de code trop long (à savoir 20 lignes ou plus) ou fichier joint directement sur Discord tout en supprimant le message original.
```

2021-01-31 11:15 UTC, AntoineJT commented on README.md
> +Cela a pour but d'éviter les messages trop longs dans les salons de langage (le bot n'est actif que dans les catégories Développement et Technique).
Meilleure formulation des phrases
```suggestion
Au bout d'un certain nombre de lignes, il est plus facile de lire le code sur un service de bin plutôt que directement dans un salon Discord.  
Ainsi, le bot, actif uniquement dans les catégories Développement et Technique, permet d'éviter les messages désagréablement trop longs dans les salons de langages.
```

2021-01-31 11:15 UTC, AntoineJT commented on README.md
> +Un bot Discord a également été fait pour créer automatiquement un bin à partir de tout snippet de code trop long (à savoir 20 lignes ou plus) ou fichier joint directement sur Discord tout en supprima
```suggestion
Comme indiqué plus haut, nous réalisons des programmes informatiques avec la communauté. Nous avons notamment réalisé notre propre service de bin.  
Un bot Discord a également été fait pour créer automatiquement un bin à partir de tout snippet de code trop long (à savoir 20 lignes ou plus) ou fichier joint directement sur Discord tout en supprimant le message originel.  
```

2021-01-31 11:15 UTC, AntoineJT commented on README.md
>  En effet, au bout d'un certain nombre de lignes, il est plus facile de lire le code sur un service de bin plutôt que directement dans un salon Discord.
```suggestion
En effet, au bout d'un certain nombre de lignes, il est plus facile de lire le code sur un service de bin plutôt que directement dans un salon Discord.  
```

2021-01-31 11:17 UTC, AntoineJT commented
> Je tiens à ce qu'on rajoute 2-3 trucs :
> 
>     * les fichiers joints détectés ne sont uploadés que s'ils sont "textuels"
> 
>     * le bot essaiera de renvoyer toutes les pièces jointes qu'il a pu obtenir dans la limite totale de Discord de 8Mo
> 
>     * il faut préciser qu'il n'y a aucune garantie quant aux bins générés à partir de blocs de code foireux, avec des échappements de backticks complètement random. Le bot est censé gérer les mêmes cas que Discord, mais il n'y a aucune garantie dessus ; s'ils veulent un bin correct, ils utilisent du markdown correct
> 
>     * si les membres tiennent vraiment à outre passer le bot, ils peuvent envoyer un premier message puis l'éditer avec leur bloc. Il faut cependant noter qu'en faisant ça, on peut leur reprocher un flood volontaire (puisqu'ils le font en connaissance de cause) et que la modération pourrait les sanctionner pour cela

J'ai volontairement évité de parler de tout ça car mon but n'est pas de faire un manuel utilisateur du bot, là on parle d'un point dans un salon nommé règlement.
Si le règlement fait 15 pages, personne ne le lira, et ce serait donc totalement contre-productif.

2021-01-31 12:16 UTC, AntoineJT commented on README.md
> +Un bot Discord a également été fait pour créer automatiquement un bin à partir de tout snippet de code trop long (à savoir 20 lignes ou plus) ou fichier textuel joint directement sur Discord tout en
```suggestion
Un bot Discord a également été fait pour créer automatiquement un bin à partir de tout snippet de code trop long (à savoir 20 lignes ou plus) ou fichier textuel joint directement sur Discord tout en supprimant le message initial.  
```

2021-01-31 12:22 UTC, Mesteery approved these changes

2021-01-31 13:00 UTC, AntoineJT approved these changes

2021-01-31 22:24 UTC, merged

2021-01-31 22:25 UTC, AntoineJT commented
Bye bye les conventionnal commits, je ne trouve pas ça pertinent du tout sur ce repo.
Tout comme le fait de commit en anglais n'est pas forcément pertinent sur un repo seulement français.
Je renommerai peut être les fichiers également, cela reste à voir.